<?xml version="1.0" encoding="utf-8"?><Database Name="EmailReport" Class="EmailDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=EmailReport;Integrated Security=True" SettingsObjectName="EmailSend.Properties.Settings" SettingsPropertyName="EmailReportConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SendDetail" Member="SendDetail">
    <Type Name="SendDetail">
      <Column Name="UserGroup" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SendType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmailServer" Member="EmailServer">
    <Type Name="EmailServer">
      <Column Name="EmailServer" Member="EmailServer1" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdminEmail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FromUser" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>